### ISSUE TITLE
Provide a systemd.service file

### ISSUE THREAD

**Issue by jernst** [storj/gateway#6]
This will make it much more likely package maintainers like myself will consider including storj into their Linux distros :-)

Moved from: https://github.com/storj/storj/issues/3757

What we did in [UBOS](https://ubos.net/): https://github.com/uboslinux/ubos-packages/blob/master/storj/systemd/storj-gateway.service

Not providing a PR for now because that also would have to be part of the documentation and I don't know where / how to do that.

**Comment by stefanbenten** [comment]
@jernst we just merged a systemd script with the linked PR.
Thank you again for your ideas!
